// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_guides_version.test.ts.

/** The version of the `@ggdna/dna-guides` package. */
export const dnaGuidesVersion = '0.1.1';
